name: Contrast Security Scan
on: [push, pull_request, repository_dispatch]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Contrast Combined Scan
        uses: andersonshatch/scan-and/sca@83c913c836fd8a4bd4313a5d315e1a3f6f70a3b0/contrast-combined-action.yml
        with:
          # Required inputs
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          apiUserName: ${{ secrets.CONTRAST_USERNAME }}
          apiServiceKey: ${{ secrets.CONTRAST_SERVICE_KEY }}
          orgId: ${{ secrets.CONTRAST_ORG_ID }}
          
          # Optional: Control which scans to run
          runSca: true
          runLocalScan: true
          
          # Optional: Common configuration
          severity: 'HIGH'
          fail: true
